import type { DiagnosticQuestion } from "../types";

/**
 * Ordered MVP question pack (~21). Follow-ups appear only when parent intensity is high.
 */
export const GENERIC_QUESTIONS: DiagnosticQuestion[] = [
    {
        id: "acquisition_entry_01",
        stage: "acquisition",
        signals: ["information_fragmentation", "visibility"],
        answerType: "channels",
        weight: 1.15,
    },
    {
        id: "acquisition_followup_01",
        stage: "acquisition",
        signals: ["follow_up", "dependency_on_people"],
        answerType: "frequency",
        weight: 1.1,
    },
    {
        id: "acquisition_retype_01",
        stage: "acquisition",
        signals: ["duplicate_entry", "manual_work"],
        answerType: "frequency",
        weight: 1,
    },
    {
        id: "conversion_docs_01",
        stage: "conversion",
        signals: ["repetitive_work", "manual_work"],
        answerType: "frequency",
        weight: 1,
    },
    {
        id: "conversion_status_01",
        stage: "conversion",
        signals: ["visibility"],
        answerType: "ease",
        weight: 1,
    },
    {
        id: "conversion_duplicate_01",
        stage: "conversion",
        signals: ["duplicate_entry"],
        answerType: "frequency",
        weight: 1,
    },
    {
        id: "delivery_manual_01",
        stage: "delivery",
        signals: ["repetitive_work", "automation_potential"],
        answerType: "frequency",
        weight: 1.2,
    },
    {
        id: "delivery_manual_fu",
        stage: "delivery",
        signals: ["repetitive_work", "coordination"],
        answerType: "yesPartialNo",
        weight: 0.8,
        followUpOf: "delivery_manual_01",
        showIfMinIntensity: 3,
    },
    {
        id: "delivery_admin_01",
        stage: "delivery",
        signals: ["manual_work", "information_access"],
        answerType: "frequency",
        weight: 1.1,
    },
    {
        id: "delivery_info_01",
        stage: "delivery",
        signals: ["information_access", "information_fragmentation"],
        answerType: "frequency",
        weight: 1,
    },
    {
        id: "coordination_chat_01",
        stage: "coordination",
        signals: ["coordination", "visibility"],
        answerType: "agreement",
        weight: 1.1,
    },
    {
        id: "coordination_updates_01",
        stage: "coordination",
        signals: ["visibility", "follow_up"],
        answerType: "frequency",
        weight: 1,
    },
    {
        id: "coordination_handoff_01",
        stage: "coordination",
        signals: ["dependency_on_people"],
        answerType: "ease",
        weight: 1.2,
    },
    {
        id: "admin_billing_01",
        stage: "admin",
        signals: ["manual_work", "reporting"],
        answerType: "frequency",
        weight: 1,
    },
    {
        id: "admin_sheets_01",
        stage: "admin",
        signals: ["reporting", "information_fragmentation"],
        answerType: "agreement",
        weight: 1.1,
    },
    {
        id: "admin_duplicate_01",
        stage: "admin",
        signals: ["duplicate_entry", "integration"],
        answerType: "frequency",
        weight: 1,
    },
    {
        id: "tools_switch_01",
        stage: "tools",
        signals: ["software_fragmentation", "manual_work"],
        answerType: "frequency",
        weight: 1.1,
    },
    {
        id: "tools_transfer_01",
        stage: "tools",
        signals: ["integration", "duplicate_entry"],
        answerType: "frequency",
        weight: 1.2,
    },
    {
        id: "tools_transfer_fu",
        stage: "tools",
        signals: ["integration", "automation_potential"],
        answerType: "yesPartialNo",
        weight: 0.8,
        followUpOf: "tools_transfer_01",
        showIfMinIntensity: 3,
    },
    {
        id: "tools_overlap_01",
        stage: "tools",
        signals: ["software_overlap"],
        answerType: "yesPartialNo",
        weight: 1,
    },
    {
        id: "team_absence_01",
        stage: "team",
        signals: ["dependency_on_people"],
        answerType: "ease",
        weight: 1.2,
    },
    {
        id: "team_memory_01",
        stage: "team",
        signals: ["follow_up", "dependency_on_people"],
        answerType: "frequency",
        weight: 1,
    },
];
